### ISSUE TITLE
UI freezes when we have multiple child resources

### ISSUE THREAD

**Issue by nati** [cloudwan/gohan_webui#323]
# Issue

UI freezes when we have multiple child resources on detail page on V2.

# How to reproduce

1. Use this schema

```
policies:
- action: '*'
  effect: allow
  id: admin_statement
  principal: admin
  resource:
    path: .*
schemas:
- description: Customers
  id: customer
  plural: customers
  schema:
    properties:
      description:
        description: Description
        permission:
        - create
        - update
        title: Description
        type: string
      id:
        description: ID
        permission:
        - create
        title: ID
        type: string
        view:
        - detail
      name:
        description: Name
        permission:
        - create
        - update
        title: Name
        type: string
      tenant_id:
        description: Tenant ID
        permission:
        - create
        title: Tenant ID
        type: string
        view:
        - detail
    propertiesOrder:
    - id
    - name
    - description
    - tenant_id
    required: []
    type: object
  singular: customer
  title: Customers
- description: Device Types
  id: device_type
  plural: device_types
  schema:
    properties:
      description:
        description: Description
        permission:
        - create
        - update
        title: Description
        type: string
      id:
        description: ID
        permission:
        - create
        title: ID
        type: string
        view:
        - detail
      name:
        description: Name
        permission:
        - create
        - update
        title: Name
        type: string
      tenant_id:
        description: Tenant ID
        permission:
        - create
        title: Tenant ID
        type: string
        view:
        - detail
    propertiesOrder:
    - id
    - name
    - description
    - tenant_id
    required: []
    type: object
  singular: device_type
  title: Device Types
- description: Devices
  id: device
  parent: customer
  plural: devices
  schema:
    properties:
      customer_id:
        description: parent object
        permission:
        - create
        relation: customer
        title: customer
        type: string
        unique: false
      description:
        description: Description
        permission:
        - create
        - update
        title: Description
        type: string
      device_type_id:
        description: Device Type
        permission:
        - create
        - update
        relation: device_type
        relation_property: device_type
        title: Device Type
        type: string
      id:
        description: ID
        permission:
        - create
        - update
        title: ID
        type: string
        view:
        - detail
      mac_address:
        description: MAC Address
        permission:
        - create
        title: MAC Address
        type: string
      name:
        description: Name
        permission:
        - create
        - update
        title: Name
        type: string
        view:
        - detail
        - list
        - create
      tenant_id:
        description: Tenant ID
        permission:
        - create
        title: Tenant ID
        type: string
        view:
        - detail
    propertiesOrder:
    - id
    - mac_address
    - name
    - description
    - tenant_id
    - customer_id
    - device_type_id
    required:
    - mac_address
    - customer_id
    type: object
  singular: device
  title: Devices
- description: Devices2
  id: device2
  parent: customer
  plural: devices2
  schema:
    properties:
      customer_id:
        description: parent object
        permission:
        - create
        relation: customer
        title: customer
        type: string
        unique: false
      description:
        description: Description
        permission:
        - create
        - update
        title: Description
        type: string
      device_type_id:
        description: Device Type
        permission:
        - create
        - update
        relation: device_type
        relation_property: device_type
        title: Device Type
        type: string
      id:
        description: ID
        permission:
        - create
        - update
        title: ID
        type: string
        view:
        - detail
      mac_address:
        description: MAC Address
        permission:
        - create
        title: MAC Address
        type: string
      name:
        description: Name
        permission:
        - create
        - update
        title: Name
        type: string
        view:
        - detail
        - list
        - create
      tenant_id:
        description: Tenant ID
        permission:
        - create
        title: Tenant ID
        type: string
        view:
        - detail
    propertiesOrder:
    - id
    - mac_address
    - name
    - description
    - tenant_id
    - customer_id
    - device_type_id
    required:
    - mac_address
    - customer_id
    type: object
  singular: device2
  title: Devices2
```

2. Create customer resource and go detail page
3. Push create button on device
